<?php

namespace App\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class FilterCsvEmailsCommand extends Command
{
    protected function configure()
    {
        $this->setName('filter:csv')
            ->setAliases(['f:csv'])
            ->setDescription('Filter valid emails from CSV file')
            ->setHelp('This command takes CSV file and makes 3 new files - with valid emails, invalid emails, and filtering summary')
            ->addArgument('filename', InputArgument::REQUIRED, 'CSV Filename');
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}